### ISSUE TITLE
Spring 以及Spring boot教程找不到页面问题

### ISSUE THREAD

**Issue by xingmeichen** [dunwu/java-tutorial#1]
老师您好，Spring以及Spring Boot教程详情页面都找不到了，404错误，请问这个课程是不继续对外开放了还是别的什么原因呢？我非常喜欢并且觉得对我的学习成长帮助很大，希望能够继续学习。

情况如下图：
![image](https://user-images.githubusercontent.com/28842289/68724731-44f21c00-05f7-11ea-973e-3db705c560d6.png)

**Comment by dunwu** [comment]
不好意思，项目以前使用 gitbook 生成电子书，现在改用 docsify 了，部分文档中的 Markdown 语义不识别。我尽量发现就修复。
感谢你的支持
