### ISSUE TITLE
教程中脑图是使用什么软件构建的？

### ISSUE THREAD

**Issue by jounghu** [dunwu/java-tutorial#25]
楼主您好，冒昧问一下脑图使用什么软件构建的

**Comment by dunwu** [comment]
@jounghu xmind

> 楼主您好，冒昧问一下脑图使用什么软件构建的

**Comment by jounghu** [comment]
> @jounghu xmind
> 
> > 楼主您好，冒昧问一下脑图使用什么软件构建的

顺便问一下楼主，你那个GitHub Pages，那个头部导航是怎么生成的呀～

**Comment by jounghu** [comment]
顺便问一下楼主，你那个GitHub Pages，那个头部导航是怎么生成的呀～

**Comment by dunwu** [comment]
@jounghu 我是用 vscode 中的 markdown 插件生成的导航

> 顺便问一下楼主，你那个GitHub Pages，那个头部导航是怎么生成的呀～
