### ISSUE TITLE
超链接丢失

### ISSUE THREAD

**Issue by sevenlok** [dunwu/java-tutorial#27]
[Java 和缓存 | JAVA-TUTORIAL (dunwu.github.io)](https://dunwu.github.io/java-tutorial/cache/#%F0%9F%93%96-%E5%86%85%E5%AE%B9)
  搜了一下找到了[缓存基本原理 | DESIGN (dunwu.github.io)](https://dunwu.github.io/design/distributed/%E5%88%86%E5%B8%83%E5%BC%8F%E7%BC%93%E5%AD%98.html#%E4%BB%80%E4%B9%88%E6%98%AF%E7%BC%93%E5%AD%98)
看到你好像不维护这个教程了。还看到有一些笔误的地方，请问还要改吗？

**Comment by dunwu** [comment]
@sevenlok 并非不维护了，只是这块好长时间没更新了。如果您有发现示例代码或文档有任何笔误，欢迎指正。
