### ISSUE TITLE
大佬太强了，刚学了几章收益良多

### ISSUE THREAD

**Issue by ZhaoChen2016** [dunwu/java-tutorial#4]
整理的很用心，解释的直接到位又不啰嗦，很适合在工作间隙看几个小节。特意来给大佬点赞，期待大佬多多发博客。建议可以发一些工作上遇到的坑，工作上比较好的一些技术实践。再次表达感谢！

**Comment by dunwu** [comment]
谢谢你的鼓励和建议。工作上遇到的问题，比较零散，一直没有好好整理，有时间我会整理分享的。
